In [2]:
%load_ext autoreload

In [83]:
%autoreload
import numpy as np
import darkhistory.electrons.ics.series as series
import darkhistory.electrons.ics.ics_spectrum as ics_spec
import darkhistory.physics as phys

np.set_printoptions(precision=6)

In [87]:
a = np.array([-1e-8,1e-4, 1])
beta = np.array([1e-8, 1e-3,1.-1e-8])
lowlim1 = np.outer((1-beta)/(2*beta), a)
lowlim2 = np.outer(-(1+beta)/(2*beta), a)
lowlim = np.maximum(lowlim1, lowlim2)
print(lowlim)
print(series.F_log_a(lowlim, a))

[[  5.000000e-01   5.000000e+03   5.000000e+07]
 [  5.005000e-06   4.995000e-02   4.995000e+02]
 [  1.000000e-08   5.000000e-13   5.000000e-09]]
(array([[ 0.0775888,  0.0,  0.0],
       [-73.7552, -3.85918,  7.30347e-217],
       [-170.577, -216.087,  1.11786]], dtype=float128), array([[ 3.84965e-11,  0.0,  0.0],
       [ 5.24232e-12,  6.02323e-11,  0.0],
       [ 2.26671e-12,  9.11894e-11,  1.47179e-11]], dtype=float128))
